#!/usr/bin/env bash

source activate blaze

# KILLED:
#nohup python main.py --id 'gamma_1000l_sc1_rc1_seed1' --gamma --train_flag --decay_start_epoch 100 --end_epoch 150 --print_interval 50 --save_epochs 10 --sc_weight 1 --rc_weight 0-0-0-0-0-0-1 --num_labeled 1000 --which_gpu 2 &


nohup python main.py --id "ladder_1000l_2000rc" --train_flag --decay_start_epoch 100 --end_epoch 150 --print_interval 50 --save_epochs 10 --rc_weights 2000-20-0.2-0.2-0.2-0.2-0.2 --sc_weight 1 --which_gpu 1 --num_labeled 1000 --seed 1 &

nohup python main.py --id 'gamma_1000l_sc1_rc1000_seed1' --gamma --train_flag --decay_start_epoch 100 --end_epoch 150 --print_interval 50 --save_epochs 10 --sc_weight 1 --rc_weight 0-0-0-0-0-0-1000 --num_labeled 1000 &

nohup python main.py --id 'gamma_1000l_sc1_rc1000_seed1' --gamma --train_flag --decay_start_epoch 100 --end_epoch 150 --print_interval 50 --save_epochs 10 --sc_weight 1 --rc_weight 0-0-0-0-0-0-1000 --num_labeled 1000 --which_gpu 2 &


nohup python main.py --id "ladder_1000l_amlp4" --train_flag --decay_start_epoch 100 --end_epoch 150 --print_interval 50 --save_epochs 10 --rc_weights 5000-50.0-0.5-0.5-0.5-0.5-0.5 --sc_weight 1 --which_gpu 2 --num_labeled 1000 --seed 1 --combinator 4-1 --combinator_sd 0.025 &
